import type { ReadingTrackerItem } from './types';

export const DUMMY_READING_TRACKER_ITEMS: ReadingTrackerItem[] = [
  {
    id: 'rt-001',
    sourcePaperId: '1',
    title: 'Attention Is All You Need',
    authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar'],
    year: 2017,
    venue: 'NeurIPS',
    tags: ['transformers', 'nlp'],
    status: 'done',
    isArchived: false,
    lastOpenedAt: '2026-02-20T09:30:00.000Z',
  },
  {
    id: 'rt-002',
    sourcePaperId: '4',
    title: 'Deep Residual Learning for Image Recognition',
    authors: ['Kaiming He', 'Xiangyu Zhang', 'Shaoqing Ren'],
    year: 2016,
    venue: 'CVPR',
    tags: ['vision', 'resnet'],
    status: 'reading',
    isArchived: false,
    lastOpenedAt: '2026-02-22T15:10:00.000Z',
  },
  {
    id: 'rt-003',
    sourcePaperId: '7',
    title: 'LoRA: Low-Rank Adaptation of Large Language Models',
    authors: ['Edward J. Hu', 'Yelong Shen', 'Phillip Wallis'],
    year: 2022,
    venue: 'ICLR',
    tags: ['llm', 'fine-tuning'],
    status: 'reading',
    isArchived: false,
    lastOpenedAt: '2026-02-23T08:45:00.000Z',
  },
  {
    id: 'rt-004',
    sourcePaperId: '8',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
    authors: ['Patrick Lewis', 'Ethan Perez', 'Aleksandara Piktus'],
    year: 2020,
    venue: 'NeurIPS',
    tags: ['rag', 'nlp'],
    status: 'backlog',
    isArchived: false,
  },
  {
    id: 'rt-005',
    title: 'Segment Anything',
    authors: ['Alexander Kirillov', 'Eric Mintun', 'Nikhila Ravi'],
    year: 2023,
    venue: 'ICCV',
    tags: ['vision', 'segmentation'],
    status: 'backlog',
    isArchived: false,
  },
  {
    id: 'rt-006',
    title: 'QLoRA: Efficient Finetuning of Quantized LLMs',
    authors: ['Tim Dettmers', 'Artidoro Pagnoni', 'Ari Holtzman'],
    year: 2023,
    venue: 'NeurIPS',
    tags: ['llm', 'quantization'],
    status: 'backlog',
    isArchived: false,
  },
];

